{% set version = "20180427" %}
{% set sha256 = "38a057d48c9e6f97319b8c8521ee4f30998e34204ba07399824ea9d6b5675768" %}

package:
  name: x264
  version: {{ version }}

source:
  fn: x264-snapshot-{{ version }}-2245-stable.tar.bz2
  url: http://download.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-{{ version }}-2245-stable.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true         # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - perl
    - nasm

test:
  commands:
    - test -f ${PREFIX}/include/x264.h         # [unix]
    - test -f ${PREFIX}/lib/libx264.a          # [unix]
    - test -f ${PREFIX}/lib/libx264.dylib      # [osx]
    - test -f ${PREFIX}/lib/libx264.so         # [linux]
    - x264 --help                              # [unix]

about:
  home: http://www.videolan.org/developers/x264.html
  license: GPL-2.0
  license_file: COPYING
  summary: A free software library for encoding video streams into the H.264/MPEG-4 AVC format.

extra:
  recipe-maintainers:
    - jakirkham
    - 183amir
    - carlodri
